Namespaces:
    =: com.mirantis.murano.services
    std: com.mirantis.murano
    sys: com.mirantis.murano.system

Name: Instance

Properties:
  name:
    Type: String
    Mandatory: true
  flavor:
    Type: String
    Mandatory: true
  image:
    Type: String
    Mandatory: true

Workflow:
  deploy:
    Arguments:
      - environment:
          Type: std:Environment
    Body:
      - $template:
          Resources:
            $.name:
              Type: 'AWS::EC2::Instance'
              Properties:
                InstanceType: $.flavor
                ImageId: $.image
      - $.heat.updateStack(template => $template,
          environment => $.environment)



