Namespaces:
  =: com.mirantis.murano.services
  std: com.mirantis.murano
  sys: com.mirantis.murano.system

Name: Instance

Properties:
  name:
    Contract: $.string().notNull()
  flavor:
    Contract: $.string().notNull()
  image:
    Contract: $.string().notNull()

  agent:
    Contract: $.class(sys:Agent)

Workflow:
  initialize:
    Body:
      - $.environment: $.find(std:Environment).require()
      - $.agent: new(sys:Agent, host => $)

  deploy:
    Body:
      - $resources: new(sys:Resources)
      - $template:
          Resources:
            $.name:
              Type: 'AWS::EC2::Instance'
              Properties:
                InstanceType: $.flavor
                ImageId: $.image
      - $.environment.stack.updateTemplate($template)
      - $.environment.stack.push()



